sonar:
  image: siamaksade/sonar
  ports:
    - "9000:9000"
nexus:
  image: siamaksade/nexus:2.8.1
  ports:
    - "8081:8081"
jenkins:
  image: ivanthelad/jenkins-ci:6
  links:
     - nexus:nexus
     - sonar:sonar
  ports:
    - "8080:8080"

